# Generated by Django 5.2 on 2025-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='main_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='sub_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
