# Generated by Django 5.2 on 2025-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diary_main_emotion_diary_sub_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
