# Generated by Django 5.2.1 on 2025-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='emotion_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='summary_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
