# Generated by Django 5.2.1 on 2025-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_movie_created_at_remove_movie_sub_emotions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_emotions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='nightdiary',
            name='sub_emotion',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
