# Generated by Django 5.2.1 on 2025-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_book_sub_emotions_alter_nightdiary_sub_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='sub_emotion',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
    ]
