# Generated by Django 5.2.1 on 2025-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_diary_sub_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='sub_emotion',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
