# Generated by Django 5.2.1 on 2025-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_diary_sub_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sub_emotions',
            new_name='sub_emotion',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='analysis',
        ),
    ]
